name: example
toolchainRegion: us-east-1
groups:
  - name: mygroup
    path: manifests/mymodule.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true