name: examples
toolchainRegion: us-east-1
groups:
  - name: optionals
    path: manifests/examples/optional-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true

